apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservices-deployment
  labels:
    app: cartservices-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cartservices-deployment
  template:
    metadata:
      labels:
        app: cartservices-deployment
    spec:
      containers:
      - name: cart-services-container
        image: cart_services:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5500

---
apiVersion: v1
kind: Service
metadata:
  name: cartservices-service
spec:
  selector:
    app: cartservices-deployment
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cartservices-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /cart
        pathType: Prefix
        backend:
          service:
            name: cartservices-service
            port:
              number: 5500