
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset # a cambiar
spec:
  selector:
    matchLabels:
      app: rabbitmq-deployment # a cambiar
  serviceName: "rabbitmq-service" #  a cambiar
  replicas: 3
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        app: rabbitmq-deployment # a cambiar
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.24
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-configmap
data:
# aqui van las env como key y value (como un obj)
