apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservices-deployment
  labels:
    app: userservices-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userservices-deployment
  template:
    metadata:
      labels:
        app: userservices-deployment
    spec:
      containers:
      - name: user-services-container
        image: user_services:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3030

---
apiVersion: v1
kind: Service
metadata:
  name: userservices-service
spec:
  selector:
    app: userservices-deployment
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userservices-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: userservices-service
            port:
              number: 3030


